name: Workflow Name

# Trigger events
on:
  workflow_dispatch:

# Define jobs
jobs:
  test_job_1:  # Name of the job (can be any name)
    runs-on: ubuntu-latest  # The environment where the job runs (you can choose other OS types like windows-latest or macos-latest)

    # Steps to run within the job
    steps:
      - name: Checking out a repository
        uses: actions/checkout@v2  # Checks out the code

      - name: Checking out another repository
        uses: actions/checkout@v2  # Checks out the code
       
        with:
          repository: 'dkojo/springboot-app-ecs'
          ref: 'testbranch'

      - name: Set up Node.js
        uses: actions/setup-node@v2  # Example for setting up Node.js (if your project is Node.js)

        with:
          node-version: '14'  # Specify the version of Node.js you want
    


      - name: Install dependencies
        run: npm install  # Run the npm install command

  
  test_job_2:  # Name of the job (can be any name)
    needs: test_job_1
    runs-on: ubuntu-latest  # The environment where the job runs (you can choose other OS types like windows-latest or macos-latest)

    # Steps to run within the job
    steps:
      - name: Checking out a repository
        uses: actions/checkout@v2  # Checks out the code

      - name: Checking out another repository
        uses: actions/checkout@v2  # Checks out the code